version: "3.2"
services:
  db:
    image: mariadb:latest
    container_name: mariadb
    restart: unless-stopped
    command: --transaction-isolation=READ-COMMITTED --log-bin=binlog --binlog-format=ROW
    ports:
      - "3308:3306"
    volumes:
      - ./init:/docker-entrypoint-initdb.d
      - ./data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: sample
      MYSQL_USER: user
      MYSQL_PASSWORD: 1234
  redis:
    image: redis
    container_name: redis
    command: redis-server --appendonly no --databases 1 --maxmemory 2G --maxmemory-policy allkeys-lru
    restart: unless-stopped
    ports:
      - "6379:6379"
