spring:
  profiles:
    active: local
---
spring:
  output:
    ansi:
      enabled: always
  application:
    name: webflux-coroutine
  r2dbc:
    url: r2dbc:pool:mariadb://localhost:3308/sample
    username: user
    password: 1234
  sql:
    init:
      mode: always
      schema-locations: classpath:db-init/schema.sql
logging:
  level:
    com.study: debug
    org.springframework.r2dbc.core: debug
    org.springframework.r2dbc.connection.init: debug
    org.springframework.boot.autoconfigure.web.reactive.error.AbstractErrorWebExceptionHandler: off
    org.springframework.web.HttpLogging: off
  pattern:
    #    console: "%d{HH:mm:ss.SSS}|%highlight(%-5level)|%X{txid:-}|%green(%t)|%logger|%blue(\\(%F:%L\\))|%msg%n"
    console: "%d{HH:mm:ss.SSS}|%highlight(%-5level)|%X{txid:-}|%green(%t)|%blue(\\(%F:%L\\))|%msg%n"
api:
  externalUrl: http://localhost:8091
---
spring:
  config:
    activate:
      on-profile: local
  r2dbc:
    url: r2dbc:pool:h2:file:///./sample
  #    url: r2dbc:pool:h2:mem://localhost/sample
  sql:
    init:
      mode: always
      data-locations: classpath:db-init/test.sql
server:
  error:
    include-exception: true # exception 의 종류를 출력
    # always 는 항상, on_param 옵션은 파라미터로 path/error?message&trace&errors 등을 추가해야 값을 보여줌.
    include-message: on_param # exception 의 message 를 출력
    include-stacktrace: on_param # exception 의 stacktrace 를 출력
    include-binding-errors: on_param # valid exception 이 발생하면 어떤 필드가 문제인지 출력
---
spring:
  config:
    activate:
      on-profile: test
  r2dbc:
    url: r2dbc:pool:h2:mem://localhost/sample
  sql:
    init:
      mode: embedded
---
spring:
  config:
    activate:
      on-profile: stress
  sql:
    init:
      mode: never
logging:
  level:
    com.study: debug
    org.springframework.r2dbc.core: off
    org.springframework.r2dbc.connection.init: off
---
spring:
  config:
    activate:
      on-profile: prod
server:
  error:
    include-stacktrace: never